# Generated by Django 4.0.3 on 2022-04-05 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youfood', '0003_videodemo_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='videodemo',
        ),
    ]
