# Generated by Django 3.1.7 on 2021-05-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youfoodapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooddata',
            name='category',
            field=models.CharField(default='nothing', max_length=200),
        ),
    ]
