# Generated by Django 3.1.7 on 2021-05-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youfoodapp', '0003_auto_20210505_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooddata',
            name='category',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=200),
        ),
    ]
