# Generated by Django 3.2.2 on 2021-05-11 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youfoodapp', '0005_auto_20210505_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooddata',
            name='discription',
            field=models.TextField(default='no dicription', max_length=500),
        ),
    ]
