# Generated by Django 3.2.2 on 2021-05-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youfoodapp', '0007_alter_fooddata_discription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooddata',
            name='discription',
            field=models.TextField(null=True),
        ),
    ]
