# Generated by Django 3.2.2 on 2021-05-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youfoodapp', '0008_alter_fooddata_discription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooddata',
            name='category',
            field=models.CharField(choices=[('sweet', 'sweet'), ('fastfood', 'fastfood'), ('meals', 'meals'), ('snacks', 'snacks'), ('curry', 'curry')], max_length=200),
        ),
    ]
