# Generated by Django 3.2.2 on 2021-05-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youfoodapp', '0009_alter_fooddata_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooddata',
            name='category',
            field=models.CharField(choices=[('sweets', 'sweets'), ('fastfood', 'fastfood'), ('meals', 'meals'), ('snacks', 'snacks'), ('curry', 'curry')], max_length=200),
        ),
    ]
